export { default as Header } from './header/Header';
export { default as CanvasContainer } from './Canvas/Canvas.js';
// export { default as drawSun } from './system/sun';
// export { default as drawEarth } from './system/earth';
export { default as Menu } from './menu/Menu.jsx';
// export { default as QuickView } from './quickView/QuickView.jsx';
// export { default as drawMercury } from './system/mercury';
// export { default as drawVenus } from './system/venus';
export { default as Earth } from './Canvas/Earth.jsx';
export { default as drawAsteroids } from './system/asteroids';
export { default as Inventory } from './menu/Inventory.jsx';